package com.gm.subscription;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gm.box.Box;
import com.gm.converters.BoxConverter;
import com.gm.converters.OrderConverter;
import com.gm.converters.OrderListConverter;
import com.gm.order.Order;
import com.gm.util.SubscriptionType;

import javax.persistence.*;
import java.io.Serializable;
import java.time.YearMonth;
import java.util.Objects;
import java.util.Set;

@Entity
@DynamoDBTable(tableName = "Subscription")
//@DynamoDBDocument
public class Subscription  {


    //@GeneratedValue(strategy = GenerationType.SEQUENCE)
    //@Column(name = "subscription_id")
    private long id;

    //@Enumerated(EnumType.STRING)
    //@Column(name = "type", nullable = false)

    private SubscriptionType type;

    //@Column(name = "price", nullable = false)

    private Double Price;

    //@Column(name = "yearMonth", nullable = false)

    private YearMonth subscriptionYearMonth;

    //@JsonProperty("box")
    //@OneToOne(cascade = CascadeType.ALL)
    //@JoinColumn(name = "box_id", referencedColumnName = "id")

    private Box box;

    //@JsonProperty("orders")
    //@JsonIgnore
    //@OneToMany(cascade = CascadeType.ALL,mappedBy = "user", fetch = FetchType.EAGER)
    //@DynamoDBAttribute(attributeName = "orders")
    //@DynamoDBTypeConverted(converter = OrderConverter.class)
    //private Set<Order> orders;

    public Subscription() {}
    public Subscription(SubscriptionType type, Double price, YearMonth subscriptionYearMonth, Box box) {
        this.type = type;
        Price = price;
        this.subscriptionYearMonth = subscriptionYearMonth;
        this.box = box;
    }


    @DynamoDBAttribute(attributeName = "box")
    @DynamoDBTypeConverted(converter = BoxConverter.class)
    public Box getBox() {
        return box;
    }

    public void setBox(Box box) {
        this.box = box;
    }


    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }


    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "type")
    public SubscriptionType getType() {
        return type;
    }

    public void setType(SubscriptionType type) {
        this.type = type;
    }


    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "subscriptionYearMonth")
    public YearMonth getSubscriptionYearMonth() {
        return subscriptionYearMonth;
    }

    public void setSubscriptionYearMonth(YearMonth subscriptionYearMonth) {
        this.subscriptionYearMonth = subscriptionYearMonth;
    }

    public Subscription(Subscription sub) {
        this.id = sub.id;
        this.type = sub.type;
        Price = sub.Price;
        this.subscriptionYearMonth = sub.subscriptionYearMonth;
        this.box = sub.box;
        //this.orders = sub.orders;
    }


    @DynamoDBAttribute(attributeName = "price")
    public Double getPrice() {
        return Price;
    }
    public void setPrice(Double price) {
        Price = price;
    }


    /**public Set<Order> getOrders() {
        return orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }
**/
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Subscription)) return false;
        Subscription that = (Subscription) o;
        return getId() == that.getId() &&
                getType() == that.getType() &&
                Objects.equals(getPrice(), that.getPrice()) &&
                Objects.equals(getSubscriptionYearMonth(), that.getSubscriptionYearMonth()) &&
                Objects.equals(getBox(), that.getBox());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getType(), getPrice(), getSubscriptionYearMonth(), getBox());
    }

    @Override
    public String toString() {
        return "Subscription{" +
                "id=" + id +
                ", type=" + type +
                ", Price=" + Price +
                ", subscriptionYearMonth=" + subscriptionYearMonth +
                ", box=" + box.getId() +
                '}';
    }
}